/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Answer } from './answer';

export interface Question { 
    questionId?: number;
    conditionId?: string;
    questionText?: string;
    questionType?: Question.QuestionTypeEnum;
    possibleAnswers?: Array<Answer>;
    answerScoreRange?: Array<number>;
}
export namespace Question {
    export type QuestionTypeEnum = 'open' | 'closed' | 'multiple' | 'range';
    export const QuestionTypeEnum = {
        Open: 'open' as QuestionTypeEnum,
        Closed: 'closed' as QuestionTypeEnum,
        Multiple: 'multiple' as QuestionTypeEnum,
        Range: 'range' as QuestionTypeEnum
    };
}