/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UserType { 
    id?: string;
    type?: UserType.TypeEnum;
}
export namespace UserType {
    export type TypeEnum = 'CLINITIAN' | 'PATIENT';
    export const TypeEnum = {
        CLINITIAN: 'CLINITIAN' as TypeEnum,
        PATIENT: 'PATIENT' as TypeEnum
    };
}