/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { Gp } from '../model/gp';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class GpControllerService {

    protected basePath = 'http://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Create a new GP
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createGp(body: Gp, observe?: 'body', reportProgress?: boolean): Observable<Gp>;
    public createGp(body: Gp, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Gp>>;
    public createGp(body: Gp, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Gp>>;
    public createGp(body: Gp, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling createGp.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*',
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Gp>('post',`${this.basePath}/gp`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Delete an existing GP
     * 
     * @param gpId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteGp(gpId: string, observe?: 'body', reportProgress?: boolean): Observable<Gp>;
    public deleteGp(gpId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Gp>>;
    public deleteGp(gpId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Gp>>;
    public deleteGp(gpId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (gpId === null || gpId === undefined) {
            throw new Error('Required parameter gpId was null or undefined when calling deleteGp.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*',
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Gp>('delete',`${this.basePath}/gp/${encodeURIComponent(String(gpId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get all GPs that belong to a surgery
     * 
     * @param surgeryId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllGpInSurgery(surgeryId: string, observe?: 'body', reportProgress?: boolean): Observable<Array<Gp>>;
    public getAllGpInSurgery(surgeryId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Gp>>>;
    public getAllGpInSurgery(surgeryId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Gp>>>;
    public getAllGpInSurgery(surgeryId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (surgeryId === null || surgeryId === undefined) {
            throw new Error('Required parameter surgeryId was null or undefined when calling getAllGpInSurgery.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*',
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<Gp>>('get',`${this.basePath}/gp/all/${encodeURIComponent(String(surgeryId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get a GP by its ID
     * 
     * @param gpId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getGp(gpId: string, observe?: 'body', reportProgress?: boolean): Observable<Gp>;
    public getGp(gpId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Gp>>;
    public getGp(gpId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Gp>>;
    public getGp(gpId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (gpId === null || gpId === undefined) {
            throw new Error('Required parameter gpId was null or undefined when calling getGp.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*',
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Gp>('get',`${this.basePath}/gp/${encodeURIComponent(String(gpId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update an existing GP
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateGp(body: Gp, observe?: 'body', reportProgress?: boolean): Observable<Gp>;
    public updateGp(body: Gp, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Gp>>;
    public updateGp(body: Gp, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Gp>>;
    public updateGp(body: Gp, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling updateGp.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*',
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Gp>('put',`${this.basePath}/gp`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
