/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { GpSurgery } from '../model/gpSurgery';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class GpSurgeryControllerService {

    protected basePath = 'http://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Create a new GP Surgery
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createGpSurgery(body: GpSurgery, observe?: 'body', reportProgress?: boolean): Observable<GpSurgery>;
    public createGpSurgery(body: GpSurgery, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GpSurgery>>;
    public createGpSurgery(body: GpSurgery, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GpSurgery>>;
    public createGpSurgery(body: GpSurgery, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling createGpSurgery.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*',
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<GpSurgery>('post',`${this.basePath}/gp-surgery`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Delete an existing GP Surgery
     * 
     * @param gpSurgeryId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteGpSurgery(gpSurgeryId: string, observe?: 'body', reportProgress?: boolean): Observable<GpSurgery>;
    public deleteGpSurgery(gpSurgeryId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GpSurgery>>;
    public deleteGpSurgery(gpSurgeryId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GpSurgery>>;
    public deleteGpSurgery(gpSurgeryId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (gpSurgeryId === null || gpSurgeryId === undefined) {
            throw new Error('Required parameter gpSurgeryId was null or undefined when calling deleteGpSurgery.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*',
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<GpSurgery>('delete',`${this.basePath}/gp-surgery/${encodeURIComponent(String(gpSurgeryId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get a GP Surgery by its ID
     * 
     * @param gpSurgeryId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getGpSurgery(gpSurgeryId: string, observe?: 'body', reportProgress?: boolean): Observable<GpSurgery>;
    public getGpSurgery(gpSurgeryId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GpSurgery>>;
    public getGpSurgery(gpSurgeryId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GpSurgery>>;
    public getGpSurgery(gpSurgeryId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (gpSurgeryId === null || gpSurgeryId === undefined) {
            throw new Error('Required parameter gpSurgeryId was null or undefined when calling getGpSurgery.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<GpSurgery>('get',`${this.basePath}/gp-surgery/${encodeURIComponent(String(gpSurgeryId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * List of GP Surgeries
     * 
     * @param surgeryName 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public listGpSurgeries(surgeryName: string, observe?: 'body', reportProgress?: boolean): Observable<Array<GpSurgery>>;
    public listGpSurgeries(surgeryName: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<GpSurgery>>>;
    public listGpSurgeries(surgeryName: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<GpSurgery>>>;
    public listGpSurgeries(surgeryName: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (surgeryName === null || surgeryName === undefined) {
            throw new Error('Required parameter surgeryName was null or undefined when calling listGpSurgeries.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (surgeryName !== undefined && surgeryName !== null) {
            queryParameters = queryParameters.set('surgeryName', <any>surgeryName);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*',
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<GpSurgery>>('get',`${this.basePath}/gp-surgery`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update an existing GP Surgery
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateGpSurgery(body: GpSurgery, observe?: 'body', reportProgress?: boolean): Observable<GpSurgery>;
    public updateGpSurgery(body: GpSurgery, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GpSurgery>>;
    public updateGpSurgery(body: GpSurgery, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GpSurgery>>;
    public updateGpSurgery(body: GpSurgery, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling updateGpSurgery.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*',
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<GpSurgery>('put',`${this.basePath}/gp-surgery`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
