/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { BaseUser } from '../model/baseUser';
import { Registration } from '../model/registration';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class RegistrationControllerService {

    protected basePath = 'http://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Check if a code is valid
     * 
     * @param registrationCode 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public codeValid(registrationCode: string, observe?: 'body', reportProgress?: boolean): Observable<boolean>;
    public codeValid(registrationCode: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<boolean>>;
    public codeValid(registrationCode: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<boolean>>;
    public codeValid(registrationCode: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (registrationCode === null || registrationCode === undefined) {
            throw new Error('Required parameter registrationCode was null or undefined when calling codeValid.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*',
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<boolean>('put',`${this.basePath}/register/${encodeURIComponent(String(registrationCode))}/valid`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Create a new registration code
     * 
     * @param userId 
     * @param userType 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createRegistrationCode(userId: string, userType: string, observe?: 'body', reportProgress?: boolean): Observable<Registration>;
    public createRegistrationCode(userId: string, userType: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Registration>>;
    public createRegistrationCode(userId: string, userType: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Registration>>;
    public createRegistrationCode(userId: string, userType: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (userId === null || userId === undefined) {
            throw new Error('Required parameter userId was null or undefined when calling createRegistrationCode.');
        }

        if (userType === null || userType === undefined) {
            throw new Error('Required parameter userType was null or undefined when calling createRegistrationCode.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (userType !== undefined && userType !== null) {
            queryParameters = queryParameters.set('userType', <any>userType);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*',
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Registration>('post',`${this.basePath}/register/generate/${encodeURIComponent(String(userId))}`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Link a user auth account to a user via an access code
     * 
     * @param registrationCode 
     * @param authId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public registerUser(registrationCode: string, authId: string, observe?: 'body', reportProgress?: boolean): Observable<BaseUser>;
    public registerUser(registrationCode: string, authId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<BaseUser>>;
    public registerUser(registrationCode: string, authId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<BaseUser>>;
    public registerUser(registrationCode: string, authId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (registrationCode === null || registrationCode === undefined) {
            throw new Error('Required parameter registrationCode was null or undefined when calling registerUser.');
        }

        if (authId === null || authId === undefined) {
            throw new Error('Required parameter authId was null or undefined when calling registerUser.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (registrationCode !== undefined && registrationCode !== null) {
            queryParameters = queryParameters.set('registrationCode', <any>registrationCode);
        }
        if (authId !== undefined && authId !== null) {
            queryParameters = queryParameters.set('authId', <any>authId);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*',
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<BaseUser>('put',`${this.basePath}/register`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
